name: cruise
description: "A new transportation DIMENSION."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sizer: ^3.0.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  pinput: ^5.0.1
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  bloc: ^9.0.0
  meta: ^1.15.0
  flutter_pw_validator: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/svgs/
